name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS SSO
        uses: aws-actions/configure-aws-sso@v1
        with:
          sso_start_url: ${{ secrets.AWS_SSO_START_URL }}
          sso_region: ${{ secrets.AWS_SSO_REGION }}
          sso_account_id: ${{ secrets.AWS_SSO_ACCOUNT_ID }}
          sso_role_name: ${{ secrets.AWS_SSO_ROLE_NAME }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        run: |
          cd backend
          terraform init
          terraform apply -auto-approve
