name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  test-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'backend'

      - name: Create virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend/lambda
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Test Lambda function
        run: |
          cd backend/lambda
          source env/bin/activate
          aws lambda invoke --function-name count --payload file://test-event.json output.json

      - name: Package Lambda code
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.test-lambda.result == 'success'
        run: |
          cd backend/lambda
          source env/bin/activate
          zip count.zip count.py

          # Save a hash of the zip file
          echo "$(shasum -a 256 count.zip | cut -d ' ' -f 1)" > count.zip.hash

          # Store the hash as an environment variable
          echo "HASH=$(cat count.zip.hash)" >> $GITHUB_ENV

  terraform-apply:
    needs: test-lambda
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'backend'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.4.0
      
      - name: Terraform Init
        id: init
        run: cd backend && terraform init
        working-directory: ./backend

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: cd backend && terraform apply -auto-approve -input=false
        working-directory: ./backend

